Main: Vehiculo.o Coche.o Moto.o Main.o
	g++ Vehiculo.o Coche.o Moto.o Main.o -o Main   
Vehiculo.o: Vehiculo.h Vehiculo.cc
	g++ -c Vehiculo.cc
Coche.o: Coche.h Coche.cc
	g++ -c Coche.cc
Moto.o: Moto.h Moto.cc
	g++ -c Moto.cc

Main.o: Main.cc
	g++ -c Main.cc
