Main: Triangulo.o Cuadrado.o Main.o
	g++ Triangulo.o Cuadrado.o Main.o -o Main   
Triangulo.o: Triangulo.h Triangulo.cc
	g++ -c Triangulo.cc
Cuadrado.o: Cuadrado.h Cuadrado.cc
	g++ -c Cuadrado.cc

Main.o: Main.cc
	g++ -c Main.cc
